version: '3'

services:
  cgitize:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      # Every 3 hours:
      SCHEDULE: '0 */3 * * *'
    image: egortensin/cgitize:latest
    restart: unless-stopped
    volumes:
      - ./examples/docker:/etc/cgitize:ro
      - repositories:/mnt/cgitize
  frontend:
    build:
      context: ./docker/frontend
    image: egortensin/cgitize-frontend:latest
    ports:
      - '127.0.0.1:80:80'
    restart: unless-stopped
    volumes:
      - repositories:/mnt/cgitize:ro

volumes:
  repositories:
