version: '3.4'

x-default-settings:
  &default-settings
  logging:
    driver: journald
  restart: unless-stopped

services:
  cgitize:
    << : *default-settings
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      # Every 3 hours:
      SCHEDULE: '0 */3 * * *'
    image: egortensin/cgitize:latest
    volumes:
      - ./examples/docker:/etc/cgitize:ro
      - repositories:/mnt/cgitize
  frontend:
    << : *default-settings
    build:
      context: ./docker/frontend
    image: egortensin/cgitize-frontend:latest
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - repositories:/mnt/cgitize:ro

volumes:
  repositories:
