version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: server
  client:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: client
    volumes:
      - ./client/etc/:/etc/cgit-repos:ro
      - "$SSH_AUTH_SOCK:/var/run/cgit-repos/ssh-agent.sock"
      - ./client/output:/var/tmp/cgit-repos/output
